# Form implementation generated from reading ui file 'C:\Users\anton\Documents\GitHub\Systemudvikling\GUI - XML\Studerende.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(0, 70, 801, 301))
        self.calendarWidget.setObjectName("calendarWidget")
        self.datovalg_2 = QtWidgets.QLabel(self.centralwidget)
        self.datovalg_2.setGeometry(QtCore.QRect(40, 0, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.datovalg_2.setFont(font)
        self.datovalg_2.setObjectName("datovalg_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(40, 390, 701, 151))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.datovalg = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.datovalg.setFont(font)
        self.datovalg.setObjectName("datovalg")
        self.datoindhold = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datoindhold.setFont(font)
        self.datoindhold.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.datoindhold.setWordWrap(True)
        self.datoindhold.setObjectName("datoindhold")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.datovalg_2.setText(_translate("MainWindow", "Login som studerende"))
        self.datovalg.setText(_translate("MainWindow", "Skema for mandag d. 21. marts 2022"))
        self.datoindhold.setText(_translate("MainWindow", "<html><head/><body><p>09 - 12: Systemudvikling - Theo exercise - Und.lokale - A105, HCØ</p><p>15 - 17: Systemudvikling - Lecture - Aud. - Lille UP1, DIKU</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
