# Form implementation generated from reading ui file 'C:\Users\anton\Documents\GitHub\Systemudvikling\GUI - XML\Underviser.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 595)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kalenderUnderviser = QtWidgets.QCalendarWidget(self.centralwidget)
        self.kalenderUnderviser.setGeometry(QtCore.QRect(0, 60, 961, 281))
        self.kalenderUnderviser.setObjectName("kalenderUnderviser")
        self.datovalg_2 = QtWidgets.QLabel(self.centralwidget)
        self.datovalg_2.setGeometry(QtCore.QRect(30, 0, 701, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        self.datovalg_2.setFont(font)
        self.datovalg_2.setObjectName("datovalg_2")
        self.forsporgselTid = QtWidgets.QTimeEdit(self.centralwidget)
        self.forsporgselTid.setGeometry(QtCore.QRect(570, 400, 361, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.forsporgselTid.setFont(font)
        self.forsporgselTid.setObjectName("forsporgselTid")
        self.lavForsporgsel_2 = QtWidgets.QPushButton(self.centralwidget)
        self.lavForsporgsel_2.setGeometry(QtCore.QRect(570, 470, 361, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.lavForsporgsel_2.setFont(font)
        self.lavForsporgsel_2.setMouseTracking(True)
        self.lavForsporgsel_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: rgb(250, 250, 250);\n"
"}")
        self.lavForsporgsel_2.setObjectName("lavForsporgsel_2")
        self.kursusDropdownForporgsel = QtWidgets.QComboBox(self.centralwidget)
        self.kursusDropdownForporgsel.setGeometry(QtCore.QRect(570, 430, 361, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kursusDropdownForporgsel.setFont(font)
        self.kursusDropdownForporgsel.setAutoFillBackground(False)
        self.kursusDropdownForporgsel.setStyleSheet("")
        self.kursusDropdownForporgsel.setCurrentText("")
        self.kursusDropdownForporgsel.setObjectName("kursusDropdownForporgsel")
        self.kursusDropdownForporgsel.addItem("")
        self.kursusDropdownForporgsel.addItem("")
        self.kursusDropdownForporgsel.addItem("")
        self.kursusDropdownForporgsel.addItem("")
        self.kursusDropdownForporgsel.addItem("")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(30, 360, 511, 191))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.datoValgS = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.datoValgS.setFont(font)
        self.datoValgS.setObjectName("datoValgS")
        self.datoIndholdS = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.datoIndholdS.setFont(font)
        self.datoIndholdS.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.datoIndholdS.setWordWrap(True)
        self.datoIndholdS.setObjectName("datoIndholdS")
        self.lavForsporgsel = QtWidgets.QLabel(self.centralwidget)
        self.lavForsporgsel.setGeometry(QtCore.QRect(570, 350, 361, 55))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.lavForsporgsel.setFont(font)
        self.lavForsporgsel.setObjectName("lavForsporgsel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.datovalg_2.setText(_translate("MainWindow", "Login som underviser"))
        self.forsporgselTid.setSpecialValueText(_translate("MainWindow", "Vælg tidspunkt"))
        self.lavForsporgsel_2.setText(_translate("MainWindow", "Lav forespørgsel"))
        self.kursusDropdownForporgsel.setPlaceholderText(_translate("MainWindow", "Vælg kursus"))
        self.kursusDropdownForporgsel.setItemText(0, _translate("MainWindow", "Systemudvikling - Theo exercise"))
        self.kursusDropdownForporgsel.setItemText(1, _translate("MainWindow", "Systemudvikling - Lecture"))
        self.kursusDropdownForporgsel.setItemText(2, _translate("MainWindow", "Sygedomslære - Forelæsning"))
        self.kursusDropdownForporgsel.setItemText(3, _translate("MainWindow", "Sygedomslære - SAU"))
        self.kursusDropdownForporgsel.setItemText(4, _translate("MainWindow", "Sygedomslære - Café"))
        self.datoValgS.setText(_translate("MainWindow", "Planlagte bookinger d. 21. marts 2022"))
        self.datoIndholdS.setText(_translate("MainWindow", "<html><head/><body><p>09 - 12: Systemudvikling - Theo exercise - Und.lokale - A105, HCØ</p><p>15 - 17: Systemudvikling - Lecture - Aud. - Lille UP1, DIKU</p></body></html>"))
        self.lavForsporgsel.setText(_translate("MainWindow", "Lav lokale forespørgelse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
